name: pymc-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pymc
  - seaborn
  - scikit-learn
  - arviz
  - matplotlib
  - numpy<2.0
  - scipy
  - yfinance
  - pip
  - ipykernel